#include "map_biomes.h"

void MapBiomes::_bind_methods()
{
    BIND_ENUM_CONSTANT(CLOUDS);
    BIND_ENUM_CONSTANT(SEA);
    BIND_ENUM_CONSTANT(DESERT);
    BIND_ENUM_CONSTANT(WASTELAND);
    BIND_ENUM_CONSTANT(SWAMP);
    BIND_ENUM_CONSTANT(STEPPE);
    BIND_ENUM_CONSTANT(PLAINS);
    BIND_ENUM_CONSTANT(MOUNTAIN);
    BIND_ENUM_CONSTANT(BRUSHLAND);
    BIND_ENUM_CONSTANT(FOREST);
    BIND_ENUM_CONSTANT(SEASHORE);
}
